name: Latest blog post workflow
on:
  schedule:
    # Her saat başı çalıştır
    - cron: '0 * * * *'
  workflow_dispatch:  # Manuel çalıştırma desteği ekler
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://ramazanaltintop.github.io/atom.xml'
